---

scope: ya-cloud
name: pgsql01
namespace: /service/

log:
  level: INFO
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: 192.168.122.50:8008
  connect_address: 192.168.122.50:8008

etcd:
  hosts: 192.168.122.55:2379,192.168.122.56:2379,192.168.122.57:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 120
    loop_wait: 10
    retry_timeout: 30
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        shared_buffers : 1024MB
        effective_cache_size : 3GB
        maintenance_work_mem: 320MB
        wal_buffers: 8MB
        wal_keep_size: 2GB
        work_mem: 32MB
        min_wal_size: 1GB
        max_wal_size: 4GB
        huge_pages: off
        max_worker_processes: 4
        max_parallel_workers: 4
        max_parallel_workers_per_gather: 2
        max_parallel_maintenance_workers: 2
        autovacuum: on
        autovacuum_max_workers: 3
        autovacuum_vacuum_scale_factor: 0.08
        autovacuum_analyze_scale_factor: 0.08
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_cost_delay: 2
        autovacuum_naptime: 15s
        autovacuum_vacuum_threshold: 20
        wal_writer_delay : 200ms
        wal_writer_flush_after : 1MB
        random_page_cost: 1.25
        effective_io_concurrency: 200
        superuser_reserved_connections: 4
        password_encryption: md5
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        default_statistics_target: 1000
        seq_page_cost: 1
        synchronous_commit: on
        max_files_per_process: 1024
        archive_mode: on
        archive_timeout: 1800s
        archive_command: /bin/true
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        auto_explain.sample_rate: 0.01
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        log_connections: off
        log_disconnections: off
        log_statement: none
        logging_collector: on
        log_min_duration_statement: 5s
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p]: [%l-1] '
        log_filename: postgresql-%Y-%m-%d.log
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        jit: off
        lc_messages: en_US.UTF-8
        log_directory: /var/lib/postgresql/14/log

initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 192.168.122.50/32 md5
    - host replication replicator 192.168.122.51/32 md5
    - host replication replicator 192.168.122.52/32 md5
    - host all all 0.0.0.0/0 md5

postgresql:
  listen: 192.168.122.50,127.0.0.1:5432
  connect_address: 192.168.122.50:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/14/data
  bin_dir: /usr/lib/postgresql/14/bin
  config_dir: /var/lib/postgresql/14/data
  pgpass: /var/lib/postgresql/.pgpass_patroni

  authentication:
    replication:
      username: "replicator"
      password: "replicator"
    superuser:
      username: "postgres"
      password: "postgrespass"
    rewind:
      username: "rewind_user"
      password: "rewind"
  parameters:
    unix_socket_directories: /var/run/postgresql

  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
