apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: hello-rs-demo
spec:
    replicas: 3
    selector:
       matchLabels:
          app: hello-demo
    template:
       metadata:
          labels:
             app: hello-demo
       spec:
          containers:
          - name: hello-demo
            image: pg_kub1_app:v1
            ports:
              - containerPort: 80

