apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "app-chart.fullname" . }} 
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.user .Values.postgresql.password .Values.postgresql.host .Values.postgresql.port .Values.postgresql.db  | b64enc | quote }}

