apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
  
  
---
apiVersion: v1
kind: Service
metadata:
  name: persistent-service
spec:
  selector:
    app: persistent-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort  

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /storage($|/)(.*)
          pathType: Prefix  
          backend:
            service:
                name: persistent-service
                port: 
                    number: 9000
        - path: /state($|/)(.*)
          pathType: Prefix  
          backend:
            service:
                name: statefulset-service
                port: 
                    number: 80            
        - path: /pg($|/)(.*)
          pathType: Prefix  
          backend:
            service:
                name: pg-app
                port: 
                    number: 9000                

