apiVersion: v1
kind: Service
metadata:
  name: statefulset-service
spec:
  selector:
    app: statefulset-app
  ports:
    - protocol: TCP
      port: 80
      name: web
  clusterIP: None  
