apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5 
    
    
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: pg_kub2_config:v1  
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.     
        - name: PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysecret
                key: password        
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      ports:
          - name: web
            containerPort: 80
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: game-demo
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "game.properties"
          path: "game.properties"
    